"""Corpus census (§ Phase 1.2): one table, markdown + JSON, from ingest
manifests. The census is committed (docs/census/) — data/ never is, so this
plus the frozen-split manifest IS the corpus identity in git.
"""

import json
from pathlib import Path

from glyphos.data.ingest import processed_dir
from glyphos.data.registry import CORPORA
from glyphos.utils import paths


def load_manifest(corpus: str) -> dict | None:
    path = processed_dir(corpus) / "manifest.json"
    if not path.exists():
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def build_census() -> dict:
    rows = []
    for name, spec in CORPORA.items():
        meta = spec.meta()
        manifest = load_manifest(name)
        row = {
            "corpus": name,
            "kind": meta.kind,
            "status": "stub" if meta.kind == "stub" else ("ingested" if manifest else "pending"),
            "license": meta.license,
            "encoding": meta.encoding,
            "translation": meta.translation_lang or "-",
            "source": meta.source,
            "notes": meta.notes,
        }
        if manifest:
            row.update(
                {
                    "sentences": manifest.get("n_records"),
                    "documents": manifest.get("n_docs"),
                    "tokens_primary": manifest.get("n_tokens_primary"),
                    "data_version": manifest.get("data_version"),
                    "inventory": manifest.get("inventory"),
                }
            )
        rows.append(row)
    return {"rows": rows}


def _fmt_int(x) -> str:
    return f"{x:,}" if isinstance(x, int) else "-"


def render_markdown(census: dict) -> str:
    lines = [
        "# Corpus census",
        "",
        "Generated by `prepare_data.py census` — do not hand-edit. "
        "`data_version` is the content hash recorded in every ledger run.",
        "",
        "| corpus | kind | status | sentences | documents | tokens (primary) "
        "| translation | license | data_version |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for r in census["rows"]:
        lines.append(
            f"| {r['corpus']} | {r['kind']} | {r['status']} | {_fmt_int(r.get('sentences'))} "
            f"| {_fmt_int(r.get('documents'))} | {_fmt_int(r.get('tokens_primary'))} "
            f"| {r['translation']} | {r['license']} | {r.get('data_version', '-')} |"
        )
    lines += ["", "## Encodings & notes", ""]
    for r in census["rows"]:
        lines.append(f"- **{r['corpus']}** — {r['encoding']}. {r['notes']} (source: {r['source']})")
    inv_rows = [r for r in census["rows"] if r.get("inventory")]
    if inv_rows:
        lines += ["", "## Raw inventories", ""]
        for r in inv_rows:
            lines.append(f"### {r['corpus']}")
            lines.append("")
            lines.append("| subset | files | MB | top extensions |")
            lines.append("|---|---|---|---|")
            for subset, info in sorted(r["inventory"].items()):
                exts = ", ".join(f"{ext}:{n}" for ext, n in list(info["by_extension"].items())[:4])
                lines.append(
                    f"| {subset} | {info['files']:,} | {info['bytes'] / 1e6:.0f} | {exts} |"
                )
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_census(out_dir: Path | None = None) -> Path:
    out_dir = out_dir or (paths.repo_root() / "docs" / "census")
    out_dir.mkdir(parents=True, exist_ok=True)
    census = build_census()
    with open(out_dir / "census.json", "w", encoding="utf-8") as f:
        json.dump(census, f, indent=2, sort_keys=True, ensure_ascii=False)
        f.write("\n")
    (out_dir / "census.md").write_text(render_markdown(census), encoding="utf-8")
    return out_dir / "census.md"
